version: '2.1'
services:
  elasticsearch:
    image: "anaostio/fitness-recipes"
    hostname: "elasticsearch"
    container_name: elasticsearch-docker
    environment:
      - "discovery.type=single-node"
      - xpack.security.enabled=false
      - http.cors.enabled=true
      - http.cors.allow-origin=*
    ports:
      - "9200:9200"
    healthcheck:
      test: [ "CMD", "curl", "-u", "elastic:searchPathRules", "-f", "localhost:9200" ]
      interval: 30s
      retries: 10

  searchapi:
    container_name: searchApi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      elasticsearch:
        condition: service_healthy

  front_app:
    container_name: front_app_a
    build:
      context: ../webapp/
      dockerfile: ../webapp/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - searchapi