version: '2.1'
services:
  elasticsearch:
    image: "anaostio/fitness-recipes"
    hostname: "elasticsearch"
    container_name: elasticsearch-docker-front
    environment:
      - "discovery.type=single-node"
      - xpack.security.enabled=false
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - network.bind_host=0.0.0.0
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl -u elastic:searchPathRules -f http://elasticsearch:9200"]
      interval: 60s
      retries: 10

  backend_app:
    image: "anaostio/fitness-recipes"
    container_name: backend_app_front
    hostname: "backend"
    environment:
      - http.cors.enabled=true
      - http.cors.allow-origin=*
    ports:
      - "8080:8080"
    depends_on:
      elasticsearch:
        condition: service_healthy

  front_app:
    container_name: front_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend_app
